services:
  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: temp_db
    #      MYSQL_DATABASE: livestock_microservices_user
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis: # 👈 ADD HERE
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: dsa-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: